### ISSUE TITLE
Can't insert vectors (Error parsing 'content-type' metadata: invalid value)

### ISSUE THREAD

**Issue by zeionara** [vdaas/vald-client-python#20]
Hi, I've deployed a `vald` cluster using [instruction here](https://vald.vdaas.org/docs/tutorial/get-started/), and now trying to insert vectors using the following code:

```py
channel = grpc.insecure_channel(f'{host}:{port}')

istub = insert_pb2_grpc.InsertStub(channel)
sstub = search_pb2_grpc.SearchStub(channel)

print('opened channel')

if init:
    icfg = payload_pb2.Insert.Config(skip_strict_exist_check = True)

    for i, doc in enumerate(read_docs()):
        doc_id = f"{i}@{doc.metadata['source']}"

        # print(doc_id)
        # print(embeddings.embed_document(doc))

        vec = payload_pb2.Object.Vector(id = doc_id, vector = embeddings.embed_document(doc))
        istub.Insert(payload_pb2.Insert.Request(vector = vec, config = icfg))

scfg = payload_pb2.Search.Config(num = 10, radius = -1.0, epsilon = 0.01, timeout = 3600)
result = sstub.Search(payload_pb2.Search.Request(vector = embeddings.embed_query(text = query), config = scfg))

print(result)

channel.close()

print('closed channel')

return
```

I've expected that script inserts the document vectors into the database and performs search using the provided query. However, the actual output is the following:

```sh
opened channel
E1220 14:08:25.949464474    9902 hpack_parser.cc:999]                  Error parsing 'content-type' metadata: invalid value
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zeio/villm/villm/__main__.py", line 247, in <module>
    main()
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/villm/villm/__main__.py", line 212, in status
    istub.Insert(payload_pb2.Insert.Request(vector = vec, config = icfg))
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-12-20T14:08:25.94962146+03:00"}"
>
```

**Comment by zeionara** [comment]
The issue is solved by explicitly forwarding ports to the `deployment`:

```sh
kubectl port-forward --address 0.0.0.0 deployment/vald-lb-gateway 8086:8081
```

Another problem appeared when trying to insert vector. `grpc` payload:

```sh
id: "0_assets_quotes.txt"
vector: 0.521983922
vector: 0.806690753
vector: 0.960494757
vector: 0.289625376
vector: 0.76610744
vector: 0.704219878
vector: 0.661383033
vector: 0.11016205
vector: 0.0269367788
vector: 0.384171098
```

Sometimes the following error is printed:

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zeio/villm/villm/__main__.py", line 374, in <module>
    main()
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/villm/villm/__main__.py", line 334, in status
    istub.Insert(payload_pb2.Insert.Request(vector = vec, config = icfg))
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected
rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected
rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected
rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected
rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected
rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"rpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected\nrpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected\nrpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected\nrpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected\nrpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected\nrpc error: code = InvalidArgument desc = Insert API Incompatible Dimension Size detected", grpc_status:3, created_time:"2023-12-21T14:05:40.267455976+03:00"}"
>
```

And sometimes another one:

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zeio/villm/villm/__main__.py", line 374, in <module>
    main()
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/villm/villm/__main__.py", line 334, in status
    istub.Insert(payload_pb2.Insert.Request(vector = vec, config = icfg))
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "received metadata size exceeds soft limit (10119 vs. 8192);  :status:42B content-type:60B grpc-status:44B grpc-message:587B grpc-status-details-bin:7053B"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"received metadata size exceeds soft limit (10119 vs. 8192);  :status:42B content-type:60B grpc-status:44B grpc-message:587B grpc-status-details-bin:7053B", grpc_status:8, created_time:"2023-12-21T14:05:44.301512188+03:00"}"
>
```

**Comment by zeionara** [comment]
Seems that I had to send vectors with number of dimensions which is equal to the number of dimensions [configured for server](https://github.com/vdaas/vald/blob/main/example/helm/values.yaml#L65)
